import { Inter } from "next/font/google";
import "./globals.css";
import Header from './components/Header'
import Footer from './components/Footer'
import AuthProvider from '@/app/components/AuthProvider';


import { McLaren } from 'next/font/google'


const  mcLaren = McLaren({ subsets: ["latin"], weight: '400' });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={mcLaren.className}>

 <AuthProvider>
      <body >
      <Header />
            {children}
          <Footer />
      </body>
 </AuthProvider>
    </html>
  );
}
